services:
  - type: web
    name: zenglian-news
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: API_BASE_URL
        value: http://127.0.0.1:3001
      - key: IS_CLOUD
        value: "true"
      - key: DEEPSEEK_API_KEY
        value: sk-59d32686632a41eb8cff94f1b144921b
